dist: trusty
sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8

env:
  - PROFILE=gemflux
  - PROFILE=starrsem
  - PROFILE=starflux
  - PROFILE=markdup
  - PROFILE=rmdup

script:
  - ./test.sh